[package]
name = "rover"
version = "0.1.0"
authors = ["Rolfe Power <rolfepower4@gmail.com>"]
edition = "2018"

[dependencies]
toml = "0.5"
directories = "3.0"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking"] }
structopt = "0.3"
